spring.application.name=backend
server.port=8080

# Usamos las variables definidas en el .env
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
# Hibernate detecta el dialecto automáticamente en versiones nuevas, 
# pero puedes dejarlo si prefieres
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.hikari.maximum-pool-size=10