spring.application.name=backend

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mail Configuration (Actualizado para Resend)
spring.mail.host=smtp.resend.com
spring.mail.port=465
spring.mail.username=resend
# La contraseña ahora será la API Key que generaste (re_...)
spring.mail.password=${MAIL_PASSWORD} 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

# Tiempos de espera (Muy importante mantenerlos)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Server Configuration
server.port=8080
